all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_connection: ssh
    docker_compose_version: v2.2.3
    ansible_user: ubuntu

project:
  hosts:
    devops:
      ansible_host: "{{ SERVER_VARIABLE }}"
      ansible_port: 22
    develop:
      ansible_host: "{{ SERVER_VARIABLE }}"
      ansible_port: 22
    stage:
      ansible_host: "{{ SERVER_VARIABLE }}"
      ansible_port: 22